# Generated by Django 4.0.4 on 2022-05-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=11)),
                ('puesto', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=500)),
                ('tipo_sangre', models.CharField(max_length=3)),
                ('rfc', models.CharField(max_length=15)),
                ('curp', models.CharField(max_length=18)),
            ],
        ),
    ]
